getting commiting

diff --git a/.github/workflows/auto-pr.yml b/.github/workflows/auto-pr.yml
--- a/.github/workflows/auto-pr.yml
+++ b/.github/workflows/auto-pr.yml
@@ -4,59 +4,55 @@ on:
   workflow_dispatch:
   push:
     branches:
-      - main  
+      - main
 
 env:
   USERNAME: ${{ github.event.pusher.name }}
-  GITHUB_CONTEXT: ${{ toJson(github.event) }} 
+  GITHUB_CONTEXT: ${{ toJson(github.event) }}
 
 jobs:
   create-PR:
     runs-on: ubuntu-latest
-    steps: 
+    steps:
       - uses: actions/checkout@v3
         with:
           repository: sapiderman/seed-go
-          token: ${{ secrets.AUTO_PR_TOKEN }}  
-      
+          token: ${{ secrets.AUTO_PR_TOKEN }}
+
       - name: Update some file
-        run: |          
+        run: |
           rm README.md
           git diff-index --quiet HEAD -- || { echo "ERROR: Dirty repository found"; git status --porcelain; }
-          echo "user is: ${{ github.event.commits.commiter }}"
+          echo "event.commits is: ${{ github.event.commits }}"
           echo "username: $USERNAME"
-                
+          git commit -m "yeaah updated" --author="$USERNAME"
+          git diff-index --quiet HEAD -- || { echo "ERROR: Dirty repository found"; git status --porcelain; exit 1; }
+
       - name: Print Github Contexts
-        run: echo "$GITHUB_CONTEXT" 
-      # git commit -m "yeaah updated" --author="$USERNAME"
-      # git diff-index --quiet HEAD -- || { echo "ERROR: Dirty repository found"; git status --porcelain; exit 1; }
+        run: echo "$GITHUB_CONTEXT"
 
-      # - name: Create Pull Request
-      #   id: cpr
-      #   uses: peter-evans/create-pull-request@v4
-      #   with:
-      #     token: ${{ secrets.AUTO_PR_TOKEN }}
-      #     commit-message: Update monika-config-schema
-      #     committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
-      #     author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
-      #     base: main
-          # push-to-fork: sapiderman/seed-go
-          # branch: test/autopr-workflow
-          # title: "[PR] testing autoPR"
-          # body: |
-          #   In this PR:
-          #   - 1. workflow
-          #   - 2. fork target
+      - name: Create Pull Request
+        id: cpr
+        uses: peter-evans/create-pull-request@v4
+        with:
+          token: ${{ secrets.AUTO_PR_TOKEN }}
+          commit-message: Update monika-config-schema
+          committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
+          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
+          base: main
+          push-to-fork: sapiderman/seed-go
+          branch: test/autopr-workflow
+          title: "[PR] testing autoPR"
+          body: |
+            In this PR:
+            - 1. workflow
+            - 2. fork target
 
-          # draft: false
-          # delete-branch: true
-      
+          draft: false
+          delete-branch: true
 
       - name: Check outputs
         if: ${{ steps.cpr.outputs.pull-request-number }}
         run: |
           echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
           echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
-
-
-
