getting context

diff --git a/.github/workflows/auto-pr.yml b/.github/workflows/auto-pr.yml
--- a/.github/workflows/auto-pr.yml
+++ b/.github/workflows/auto-pr.yml
@@ -8,6 +8,7 @@ on:
 
 env:
   USERNAME: ${{ github.event.pull_request.user.login }}
+  GITHUB_CONTEXT: ${{ toJson(github) }} 
 
 jobs:
   create-PR:
@@ -22,10 +23,13 @@ jobs:
         run: |          
           rm README.md
           git diff-index --quiet HEAD -- || { echo "ERROR: Dirty repository found"; git status --porcelain; }
-          echo "${{ github.event.pull_request.user.login }}"
-          echo $USERNAME
-          git commit -m "yeaah updated" --author="$USERNAME"
-          git diff-index --quiet HEAD -- || { echo "ERROR: Dirty repository found"; git status --porcelain; exit 1; }
+          echo "user is: ${{ github.event.pull_request.user.login }}"
+          echo "username: $USERNAME"
+                
+      - name: Print Github Contexts
+        run: echo "$GITHUB_CONTEXT" 
+      # git commit -m "yeaah updated" --author="$USERNAME"
+      # git diff-index --quiet HEAD -- || { echo "ERROR: Dirty repository found"; git status --porcelain; exit 1; }
 
       # - name: Create Pull Request
       #   id: cpr
